### ISSUE TITLE
Archive artifacts "safely"

### ISSUE THREAD

**Issue by ecbftw** [distributedweaknessfiling/DWF-Database-Artifacts#1]
As discussed at length, much of the problem with the CVE is that it stores only links to researcher advisories, software vendor advisories and supporting information.  Many of these pages disappear after a short time (either because companies disappear, revamp their sites, or put it behind a paywall) and there's no good archive of important vulnerability information.

Storing the full content of any published information is an obvious technical solution, but it is fraught with legal risk.  Vendors could claim copyright on their advisories at any time and submit DMCA takedown notices.  Local "hacking" laws could make the information contraband. By "safely", I mean, how can we store artifacts while avoiding legal risks?

Some ideas:
- Work with the Internet Archive to automatically archive any links posted to the database when they are first posted.  See: https://archive-it.org/learn-more/ .  They have obviously dealt with these legal risks a lot in the past.
- Require any viewers of vulnerability information in the database accept a site terms agreement where they agree to never use the information obtained as part of a lawsuit
- Require vendors who obtain DWF numbers to submit their associated advisories to the database.  Obviously, if they are posting it themselves, then they are unlikely to sue later.  Of course this would only work if we can convince most vendors to submit their vulnerabilities to the database.  We need a carrot to encourage them to do so.

**Comment by kurtseifried** [comment]
No, it is much simpler then this. If you want something to be listed in the DWF database you have to agree to list appropriate artifacts. This means for example that a security researcher that wants to be listed then they have to supply appropriate artifacts. If a vendor wants to be listed, they have to provide appropriate artifacts. 

As for the cases where they don't provide it, the legality of fair use is quite well established in most jurisdictions so I don't foresee any problems.

**Comment by ecbftw** [comment]
Good luck getting vendors to use it then.  We'll have yet another OSVDB that... doesn't... work.  I'm done trying to help.
