### ISSUE TITLE
README should reference new terms of use

### ISSUE THREAD

**Issue by iamamoose** [distributedweaknessfiling/DWF-Database-Artifacts#14]
https://github.com/distributedweaknessfiling/DWF-Database-Artifacts/blob/master/README.md

should referencenew ToU

https://github.com/distributedweaknessfiling/DWF-Database-Artifacts/blob/master/TermsOfUse.md

**Comment by kurtseifried** [comment]
This is done

https://github.com/distributedweaknessfiling/DWF-Database-Artifacts/commit/2c02b5d18ef40fac3e8ac594a8e1be5a3d6151a6
