### ISSUE TITLE
Data to store in the master json file

### ISSUE THREAD

**Issue by kurtseifried** [distributedweaknessfiling/DWF-Database-Artifacts#2]
So the master JSON file can contain arbitrary data, the question is what data should it contain? Some things are obvious like:

* CVSSv2
* CVSSv3
* CWE of the vuln
* CPE/SWID of the products
* other standards like OVAL/XCCDF?
* Signatures for the vuln software (e.g. SHA, AV sigs)
* Signatures for attacks

So what standards/data/etc. would people like to see? Let's make a list and then figure out what to include and define how to represent the data in the JSON data

**Comment by zmanion** [comment]
I'd suggest keeping it minimal and optional to start, i.e., things that are common? Personally, I've seen and think there's some use to CVSS (the vector string, not so much the numeric score) and CWE. CPE/SWID would be great if someone is willing to look them up or can produce them easily. Some indication/detection for vulnerable software is important, not sure if that's CPE/SWID, version strings, hashes/signatures, etc.

I've not seen a lot of OVAL/XCCDF use, but that might just be my perspective

For some thinking about a more comprehensive vulnerability data model: http://tools.ietf.org/id/draft-booth-sacm-vuln-model-02.txt.

**Comment by kurtseifried** [comment]
Just to be clear we're defining what/how to store data in the JSON file, not what *MUST* be stored

**Comment by ahouseholder** [comment]
For what it's worth, I just converted our [vul data archive](https://www.cert.org/download/vul_data_archive/) into more usable JSON here: [https://github.com/CERTCC-Vulnerability-Analysis/Vulnerability-Data-Archive](https://github.com/CERTCC-Vulnerability-Analysis/Vulnerability-Data-Archive)

I don't recommend using those specific key names (they're derived from field names in a Lotus Notes application) but it should give you a pretty good idea of what we'd expect to put into a JSON version of a CERT Vulnerability Note.

We'll likely be adapting that data model as we go. We're interested to converge / integrate toward a consistent format.

-allen-

**Comment by kurtseifried** [comment]
we've moved to version 2, things are mostly settled, one major addition we need to think about is IMPACT, will being that up at the CVE summit, so closing for now.
