### ISSUE TITLE
add CVE change info to JSON artifact (REJECT/split/merge/etc)

### ISSUE THREAD

**Issue by kseifriedredhat** [distributedweaknessfiling/DWF-Database-Artifacts#26]
add field(s) for cve rejection/etc.

**Comment by kurtseifried** [comment]
2.2 added DATE_REQUESTED, DATE_ASSIGNED, DATE_PUBLIC, REQUESTER, ASSIGNER, REPLACED_BY, STATE, TITLE to root so we can generate CSV entries from the JSON artifact, MANDATORY fields, please note some are generated by the DWF (e.g. DATE_ASSIGNED).
