### ISSUE TITLE
Clarification re: Apache License

### ISSUE THREAD

**Issue by sbunify** [distributedweaknessfiling/DWF-Database-Artifacts#3]
Agree with the Apache License for DWF in general.
The current description however only addresses the path DWF -> vendors/security practicioners etc., but not vice versa.
What if a vendor or security practicioner primarily contributes their contents first - i.e. where the original data is somewhere else (on vendor's, practioner's sites), and the DWF data was derived from it?

At least vendors may claim their data being autoritative and that they may change at any time. Here, a note like "This description has been altered from the original provided by the DWF" seems not be appropriate then. Instead, the DWF entry should be change too, so they are back in sync.
My view is that DWF should enforce their sub-CNAs to ensure that the entries are kept in sync...

**Comment by kurtseifried** [comment]
Vendors who want to push good data back up to the DWF of course would be welcome to do so. That's the whole point of this =).
