### ISSUE TITLE
Add "CREDIT" section

### ISSUE THREAD

**Issue by kurtseifried** [distributedweaknessfiling/DWF-Database-Artifacts#4]
Add a section to the DWF hierarchy called "CREDIT" which should contain a list of people involved (e.g. researcher, patcher, etc.). So a JSON array that contains a series of objects, objects should contains:

* Name (string) - can be real name, pseudonym, or "anonymous"
* Organization (string) - can be real name, pseudonym, or "anonymous"
* Email (string)
* Role (an array of one or more roles)

Role can be discoverer, researcher, patcher, tester, coordinator, do we need other roles?

Do we need any other information typically?

**Comment by puiterwijk** [comment]
Do we want to perhaps interpret the JSON null value for Name or Organization as "anonymous or not applicable"? That would mean that we would always have the same keys in the objects, but we don't disclose whether someone doesn't have an organization affiliation or whether it was anonymous.

**Comment by kurtseifried** [comment]
this is done, check version 2.0 JSON for details
